// Generated by rstantools.  Do not edit by hand.

/*
    baseqtl is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    baseqtl is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with baseqtl.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.18.0
#include <stan/model/model_header.hpp>
namespace model_paired_GT_nb_ase_refbias_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_paired_GT_nb_ase_refbias");
    reader.add_event(179, 177, "end", "model_paired_GT_nb_ase_refbias");
    return reader;
}
#include <stan_meta_header.hpp>
class model_paired_GT_nb_ase_refbias : public prob_grad {
private:
    int N;
    int A;
    int L;
    int K;
    int k;
    vector<vector<int> > Y;
    vector<int> g;
    vector<int> s;
    vector<int> gase;
    vector<vector<int> > m;
    vector<vector<int> > n;
    vector_d pH;
    vector<vector<double> > ai0;
    vector<vector<double> > sdai0;
    matrix_d cov;
    vector_d aveP;
    vector_d sdP;
    vector_d mixP;
public:
    model_paired_GT_nb_ase_refbias(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_paired_GT_nb_ase_refbias(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_paired_GT_nb_ase_refbias_namespace::model_paired_GT_nb_ase_refbias";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        // initialize member variables
        try {
            current_statement_begin__ = 5;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            current_statement_begin__ = 6;
            context__.validate_dims("data initialization", "A", "int", context__.to_vec());
            A = int(0);
            vals_i__ = context__.vals_i("A");
            pos__ = 0;
            A = vals_i__[pos__++];
            current_statement_begin__ = 7;
            context__.validate_dims("data initialization", "L", "int", context__.to_vec());
            L = int(0);
            vals_i__ = context__.vals_i("L");
            pos__ = 0;
            L = vals_i__[pos__++];
            current_statement_begin__ = 8;
            context__.validate_dims("data initialization", "K", "int", context__.to_vec());
            K = int(0);
            vals_i__ = context__.vals_i("K");
            pos__ = 0;
            K = vals_i__[pos__++];
            current_statement_begin__ = 9;
            context__.validate_dims("data initialization", "k", "int", context__.to_vec());
            k = int(0);
            vals_i__ = context__.vals_i("k");
            pos__ = 0;
            k = vals_i__[pos__++];
            current_statement_begin__ = 10;
            validate_non_negative_index("Y", "N", N);
            validate_non_negative_index("Y", "2", 2);
            context__.validate_dims("data initialization", "Y", "int", context__.to_vec(N,2));
            validate_non_negative_index("Y", "N", N);
            validate_non_negative_index("Y", "2", 2);
            Y = std::vector<std::vector<int> >(N,std::vector<int>(2,int(0)));
            vals_i__ = context__.vals_i("Y");
            pos__ = 0;
            size_t Y_limit_1__ = 2;
            for (size_t i_1__ = 0; i_1__ < Y_limit_1__; ++i_1__) {
                size_t Y_limit_0__ = N;
                for (size_t i_0__ = 0; i_0__ < Y_limit_0__; ++i_0__) {
                    Y[i_0__][i_1__] = vals_i__[pos__++];
                }
            }
            current_statement_begin__ = 11;
            validate_non_negative_index("g", "N", N);
            context__.validate_dims("data initialization", "g", "int", context__.to_vec(N));
            validate_non_negative_index("g", "N", N);
            g = std::vector<int>(N,int(0));
            vals_i__ = context__.vals_i("g");
            pos__ = 0;
            size_t g_limit_0__ = N;
            for (size_t i_0__ = 0; i_0__ < g_limit_0__; ++i_0__) {
                g[i_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 12;
            validate_non_negative_index("s", "A", A);
            context__.validate_dims("data initialization", "s", "int", context__.to_vec(A));
            validate_non_negative_index("s", "A", A);
            s = std::vector<int>(A,int(0));
            vals_i__ = context__.vals_i("s");
            pos__ = 0;
            size_t s_limit_0__ = A;
            for (size_t i_0__ = 0; i_0__ < s_limit_0__; ++i_0__) {
                s[i_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 13;
            validate_non_negative_index("gase", "A", A);
            context__.validate_dims("data initialization", "gase", "int", context__.to_vec(A));
            validate_non_negative_index("gase", "A", A);
            gase = std::vector<int>(A,int(0));
            vals_i__ = context__.vals_i("gase");
            pos__ = 0;
            size_t gase_limit_0__ = A;
            for (size_t i_0__ = 0; i_0__ < gase_limit_0__; ++i_0__) {
                gase[i_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 14;
            validate_non_negative_index("m", "A", A);
            validate_non_negative_index("m", "2", 2);
            context__.validate_dims("data initialization", "m", "int", context__.to_vec(A,2));
            validate_non_negative_index("m", "A", A);
            validate_non_negative_index("m", "2", 2);
            m = std::vector<std::vector<int> >(A,std::vector<int>(2,int(0)));
            vals_i__ = context__.vals_i("m");
            pos__ = 0;
            size_t m_limit_1__ = 2;
            for (size_t i_1__ = 0; i_1__ < m_limit_1__; ++i_1__) {
                size_t m_limit_0__ = A;
                for (size_t i_0__ = 0; i_0__ < m_limit_0__; ++i_0__) {
                    m[i_0__][i_1__] = vals_i__[pos__++];
                }
            }
            current_statement_begin__ = 15;
            validate_non_negative_index("n", "L", L);
            validate_non_negative_index("n", "2", 2);
            context__.validate_dims("data initialization", "n", "int", context__.to_vec(L,2));
            validate_non_negative_index("n", "L", L);
            validate_non_negative_index("n", "2", 2);
            n = std::vector<std::vector<int> >(L,std::vector<int>(2,int(0)));
            vals_i__ = context__.vals_i("n");
            pos__ = 0;
            size_t n_limit_1__ = 2;
            for (size_t i_1__ = 0; i_1__ < n_limit_1__; ++i_1__) {
                size_t n_limit_0__ = L;
                for (size_t i_0__ = 0; i_0__ < n_limit_0__; ++i_0__) {
                    n[i_0__][i_1__] = vals_i__[pos__++];
                }
            }
            current_statement_begin__ = 16;
            validate_non_negative_index("pH", "L", L);
            context__.validate_dims("data initialization", "pH", "vector_d", context__.to_vec(L));
            validate_non_negative_index("pH", "L", L);
            pH = vector_d(static_cast<Eigen::VectorXd::Index>(L));
            vals_r__ = context__.vals_r("pH");
            pos__ = 0;
            size_t pH_i_vec_lim__ = L;
            for (size_t i_vec__ = 0; i_vec__ < pH_i_vec_lim__; ++i_vec__) {
                pH[i_vec__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 17;
            validate_non_negative_index("ai0", "L", L);
            validate_non_negative_index("ai0", "2", 2);
            context__.validate_dims("data initialization", "ai0", "double", context__.to_vec(L,2));
            validate_non_negative_index("ai0", "L", L);
            validate_non_negative_index("ai0", "2", 2);
            ai0 = std::vector<std::vector<double> >(L,std::vector<double>(2,double(0)));
            vals_r__ = context__.vals_r("ai0");
            pos__ = 0;
            size_t ai0_limit_1__ = 2;
            for (size_t i_1__ = 0; i_1__ < ai0_limit_1__; ++i_1__) {
                size_t ai0_limit_0__ = L;
                for (size_t i_0__ = 0; i_0__ < ai0_limit_0__; ++i_0__) {
                    ai0[i_0__][i_1__] = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 18;
            validate_non_negative_index("sdai0", "L", L);
            validate_non_negative_index("sdai0", "2", 2);
            context__.validate_dims("data initialization", "sdai0", "double", context__.to_vec(L,2));
            validate_non_negative_index("sdai0", "L", L);
            validate_non_negative_index("sdai0", "2", 2);
            sdai0 = std::vector<std::vector<double> >(L,std::vector<double>(2,double(0)));
            vals_r__ = context__.vals_r("sdai0");
            pos__ = 0;
            size_t sdai0_limit_1__ = 2;
            for (size_t i_1__ = 0; i_1__ < sdai0_limit_1__; ++i_1__) {
                size_t sdai0_limit_0__ = L;
                for (size_t i_0__ = 0; i_0__ < sdai0_limit_0__; ++i_0__) {
                    sdai0[i_0__][i_1__] = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 20;
            validate_non_negative_index("cov", "N", N);
            validate_non_negative_index("cov", "(1 + K)", (1 + K));
            context__.validate_dims("data initialization", "cov", "matrix_d", context__.to_vec(N,(1 + K)));
            validate_non_negative_index("cov", "N", N);
            validate_non_negative_index("cov", "(1 + K)", (1 + K));
            cov = matrix_d(static_cast<Eigen::VectorXd::Index>(N),static_cast<Eigen::VectorXd::Index>((1 + K)));
            vals_r__ = context__.vals_r("cov");
            pos__ = 0;
            size_t cov_m_mat_lim__ = N;
            size_t cov_n_mat_lim__ = (1 + K);
            for (size_t n_mat__ = 0; n_mat__ < cov_n_mat_lim__; ++n_mat__) {
                for (size_t m_mat__ = 0; m_mat__ < cov_m_mat_lim__; ++m_mat__) {
                    cov(m_mat__,n_mat__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 23;
            validate_non_negative_index("aveP", "k", k);
            context__.validate_dims("data initialization", "aveP", "vector_d", context__.to_vec(k));
            validate_non_negative_index("aveP", "k", k);
            aveP = vector_d(static_cast<Eigen::VectorXd::Index>(k));
            vals_r__ = context__.vals_r("aveP");
            pos__ = 0;
            size_t aveP_i_vec_lim__ = k;
            for (size_t i_vec__ = 0; i_vec__ < aveP_i_vec_lim__; ++i_vec__) {
                aveP[i_vec__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 24;
            validate_non_negative_index("sdP", "k", k);
            context__.validate_dims("data initialization", "sdP", "vector_d", context__.to_vec(k));
            validate_non_negative_index("sdP", "k", k);
            sdP = vector_d(static_cast<Eigen::VectorXd::Index>(k));
            vals_r__ = context__.vals_r("sdP");
            pos__ = 0;
            size_t sdP_i_vec_lim__ = k;
            for (size_t i_vec__ = 0; i_vec__ < sdP_i_vec_lim__; ++i_vec__) {
                sdP[i_vec__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 25;
            validate_non_negative_index("mixP", "k", k);
            context__.validate_dims("data initialization", "mixP", "vector_d", context__.to_vec(k));
            validate_non_negative_index("mixP", "k", k);
            mixP = vector_d(static_cast<Eigen::VectorXd::Index>(k));
            vals_r__ = context__.vals_r("mixP");
            pos__ = 0;
            size_t mixP_i_vec_lim__ = k;
            for (size_t i_vec__ = 0; i_vec__ < mixP_i_vec_lim__; ++i_vec__) {
                mixP[i_vec__] = vals_r__[pos__++];
            }
            // validate, data variables
            current_statement_begin__ = 5;
            check_greater_or_equal(function__,"N",N,0);
            current_statement_begin__ = 6;
            check_greater_or_equal(function__,"A",A,0);
            current_statement_begin__ = 7;
            check_greater_or_equal(function__,"L",L,0);
            current_statement_begin__ = 8;
            check_greater_or_equal(function__,"K",K,0);
            current_statement_begin__ = 9;
            check_greater_or_equal(function__,"k",k,0);
            current_statement_begin__ = 10;
            current_statement_begin__ = 11;
            current_statement_begin__ = 12;
            current_statement_begin__ = 13;
            current_statement_begin__ = 14;
            current_statement_begin__ = 15;
            current_statement_begin__ = 16;
            current_statement_begin__ = 17;
            current_statement_begin__ = 18;
            current_statement_begin__ = 20;
            current_statement_begin__ = 23;
            current_statement_begin__ = 24;
            current_statement_begin__ = 25;
            // initialize data variables
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 38;
            ++num_params_r__;
            current_statement_begin__ = 39;
            ++num_params_r__;
            current_statement_begin__ = 40;
            ++num_params_r__;
            current_statement_begin__ = 41;
            ++num_params_r__;
            current_statement_begin__ = 42;
            ++num_params_r__;
            current_statement_begin__ = 43;
            ++num_params_r__;
            current_statement_begin__ = 44;
            validate_non_negative_index("betas", "(K - 1)", (K - 1));
            num_params_r__ += (K - 1);
            current_statement_begin__ = 45;
        validate_non_negative_index("rai0", "L", L);
            validate_non_negative_index("rai0", "2", 2);
            num_params_r__ += L * 2;
            current_statement_begin__ = 46;
            validate_non_negative_index("ui", "N", N);
            num_params_r__ += N;
            current_statement_begin__ = 47;
            validate_non_negative_index("uasei", "A", A);
            num_params_r__ += A;
            current_statement_begin__ = 48;
            ++num_params_r__;
            current_statement_begin__ = 49;
            ++num_params_r__;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_paired_GT_nb_ase_refbias() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        if (!(context__.contains_r("anorm")))
            throw std::runtime_error("variable anorm missing");
        vals_r__ = context__.vals_r("anorm");
        pos__ = 0U;
        context__.validate_dims("initialization", "anorm", "double", context__.to_vec());
        double anorm(0);
        anorm = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(anorm);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable anorm: ") + e.what());
        }
        if (!(context__.contains_r("apso")))
            throw std::runtime_error("variable apso missing");
        vals_r__ = context__.vals_r("apso");
        pos__ = 0U;
        context__.validate_dims("initialization", "apso", "double", context__.to_vec());
        double apso(0);
        apso = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(apso);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable apso: ") + e.what());
        }
        if (!(context__.contains_r("ba")))
            throw std::runtime_error("variable ba missing");
        vals_r__ = context__.vals_r("ba");
        pos__ = 0U;
        context__.validate_dims("initialization", "ba", "double", context__.to_vec());
        double ba(0);
        ba = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(ba);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable ba: ") + e.what());
        }
        if (!(context__.contains_r("bd")))
            throw std::runtime_error("variable bd missing");
        vals_r__ = context__.vals_r("bd");
        pos__ = 0U;
        context__.validate_dims("initialization", "bd", "double", context__.to_vec());
        double bd(0);
        bd = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(bd);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable bd: ") + e.what());
        }
        if (!(context__.contains_r("phi")))
            throw std::runtime_error("variable phi missing");
        vals_r__ = context__.vals_r("phi");
        pos__ = 0U;
        context__.validate_dims("initialization", "phi", "double", context__.to_vec());
        double phi(0);
        phi = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,phi);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable phi: ") + e.what());
        }
        if (!(context__.contains_r("theta")))
            throw std::runtime_error("variable theta missing");
        vals_r__ = context__.vals_r("theta");
        pos__ = 0U;
        context__.validate_dims("initialization", "theta", "double", context__.to_vec());
        double theta(0);
        theta = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,theta);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable theta: ") + e.what());
        }
        if (!(context__.contains_r("betas")))
            throw std::runtime_error("variable betas missing");
        vals_r__ = context__.vals_r("betas");
        pos__ = 0U;
        validate_non_negative_index("betas", "(K - 1)", (K - 1));
        context__.validate_dims("initialization", "betas", "vector_d", context__.to_vec((K - 1)));
        vector_d betas(static_cast<Eigen::VectorXd::Index>((K - 1)));
        for (int j1__ = 0U; j1__ < (K - 1); ++j1__)
            betas(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(betas);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable betas: ") + e.what());
        }
        if (!(context__.contains_r("rai0")))
            throw std::runtime_error("variable rai0 missing");
        vals_r__ = context__.vals_r("rai0");
        pos__ = 0U;
        validate_non_negative_index("rai0", "L", L);
        validate_non_negative_index("rai0", "2", 2);
        context__.validate_dims("initialization", "rai0", "matrix_d", context__.to_vec(L,2));
        matrix_d rai0(static_cast<Eigen::VectorXd::Index>(L),static_cast<Eigen::VectorXd::Index>(2));
        for (int j2__ = 0U; j2__ < 2; ++j2__)
            for (int j1__ = 0U; j1__ < L; ++j1__)
                rai0(j1__,j2__) = vals_r__[pos__++];
        try {
            writer__.matrix_unconstrain(rai0);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable rai0: ") + e.what());
        }
        if (!(context__.contains_r("ui")))
            throw std::runtime_error("variable ui missing");
        vals_r__ = context__.vals_r("ui");
        pos__ = 0U;
        validate_non_negative_index("ui", "N", N);
        context__.validate_dims("initialization", "ui", "vector_d", context__.to_vec(N));
        vector_d ui(static_cast<Eigen::VectorXd::Index>(N));
        for (int j1__ = 0U; j1__ < N; ++j1__)
            ui(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(ui);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable ui: ") + e.what());
        }
        if (!(context__.contains_r("uasei")))
            throw std::runtime_error("variable uasei missing");
        vals_r__ = context__.vals_r("uasei");
        pos__ = 0U;
        validate_non_negative_index("uasei", "A", A);
        context__.validate_dims("initialization", "uasei", "vector_d", context__.to_vec(A));
        vector_d uasei(static_cast<Eigen::VectorXd::Index>(A));
        for (int j1__ = 0U; j1__ < A; ++j1__)
            uasei(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(uasei);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable uasei: ") + e.what());
        }
        if (!(context__.contains_r("sdnb")))
            throw std::runtime_error("variable sdnb missing");
        vals_r__ = context__.vals_r("sdnb");
        pos__ = 0U;
        context__.validate_dims("initialization", "sdnb", "double", context__.to_vec());
        double sdnb(0);
        sdnb = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,sdnb);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable sdnb: ") + e.what());
        }
        if (!(context__.contains_r("sdase")))
            throw std::runtime_error("variable sdase missing");
        vals_r__ = context__.vals_r("sdase");
        pos__ = 0U;
        context__.validate_dims("initialization", "sdase", "double", context__.to_vec());
        double sdase(0);
        sdase = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,sdase);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable sdase: ") + e.what());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            // model parameters
            stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);
            local_scalar_t__ anorm;
            (void) anorm;  // dummy to suppress unused var warning
            if (jacobian__)
                anorm = in__.scalar_constrain(lp__);
            else
                anorm = in__.scalar_constrain();
            local_scalar_t__ apso;
            (void) apso;  // dummy to suppress unused var warning
            if (jacobian__)
                apso = in__.scalar_constrain(lp__);
            else
                apso = in__.scalar_constrain();
            local_scalar_t__ ba;
            (void) ba;  // dummy to suppress unused var warning
            if (jacobian__)
                ba = in__.scalar_constrain(lp__);
            else
                ba = in__.scalar_constrain();
            local_scalar_t__ bd;
            (void) bd;  // dummy to suppress unused var warning
            if (jacobian__)
                bd = in__.scalar_constrain(lp__);
            else
                bd = in__.scalar_constrain();
            local_scalar_t__ phi;
            (void) phi;  // dummy to suppress unused var warning
            if (jacobian__)
                phi = in__.scalar_lb_constrain(0,lp__);
            else
                phi = in__.scalar_lb_constrain(0);
            local_scalar_t__ theta;
            (void) theta;  // dummy to suppress unused var warning
            if (jacobian__)
                theta = in__.scalar_lb_constrain(0,lp__);
            else
                theta = in__.scalar_lb_constrain(0);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  betas;
            (void) betas;  // dummy to suppress unused var warning
            if (jacobian__)
                betas = in__.vector_constrain((K - 1),lp__);
            else
                betas = in__.vector_constrain((K - 1));
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,Eigen::Dynamic>  rai0;
            (void) rai0;  // dummy to suppress unused var warning
            if (jacobian__)
                rai0 = in__.matrix_constrain(L,2,lp__);
            else
                rai0 = in__.matrix_constrain(L,2);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  ui;
            (void) ui;  // dummy to suppress unused var warning
            if (jacobian__)
                ui = in__.vector_constrain(N,lp__);
            else
                ui = in__.vector_constrain(N);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  uasei;
            (void) uasei;  // dummy to suppress unused var warning
            if (jacobian__)
                uasei = in__.vector_constrain(A,lp__);
            else
                uasei = in__.vector_constrain(A);
            local_scalar_t__ sdnb;
            (void) sdnb;  // dummy to suppress unused var warning
            if (jacobian__)
                sdnb = in__.scalar_lb_constrain(0,lp__);
            else
                sdnb = in__.scalar_lb_constrain(0);
            local_scalar_t__ sdase;
            (void) sdase;  // dummy to suppress unused var warning
            if (jacobian__)
                sdase = in__.scalar_lb_constrain(0,lp__);
            else
                sdase = in__.scalar_lb_constrain(0);
            // transformed parameters
            current_statement_begin__ = 54;
            local_scalar_t__ bp;
            (void) bp;  // dummy to suppress unused var warning
            stan::math::initialize(bp, DUMMY_VAR__);
            stan::math::fill(bp,DUMMY_VAR__);
            current_statement_begin__ = 55;
            local_scalar_t__ bn;
            (void) bn;  // dummy to suppress unused var warning
            stan::math::initialize(bn, DUMMY_VAR__);
            stan::math::fill(bn,DUMMY_VAR__);
            current_statement_begin__ = 57;
            stan::math::assign(bp, (ba + bd));
            current_statement_begin__ = 58;
            stan::math::assign(bn, (ba - bd));
            // validate transformed parameters
            if (stan::math::is_uninitialized(bp)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: bp";
                throw std::runtime_error(msg__.str());
            }
            if (stan::math::is_uninitialized(bn)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: bn";
                throw std::runtime_error(msg__.str());
            }
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 54;
            current_statement_begin__ = 55;
            // model body
            {
            current_statement_begin__ = 63;
            int pos(0);
            (void) pos;  // dummy to suppress unused var warning
            stan::math::fill(pos, std::numeric_limits<int>::min());
            current_statement_begin__ = 64;
            int posl(0);
            (void) posl;  // dummy to suppress unused var warning
            stan::math::fill(posl, std::numeric_limits<int>::min());
            current_statement_begin__ = 65;
            validate_non_negative_index("lmu1", "N", N);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  lmu1(static_cast<Eigen::VectorXd::Index>(N));
            (void) lmu1;  // dummy to suppress unused var warning
            stan::math::initialize(lmu1, DUMMY_VAR__);
            stan::math::fill(lmu1,DUMMY_VAR__);
            current_statement_begin__ = 66;
            local_scalar_t__ lmu;
            (void) lmu;  // dummy to suppress unused var warning
            stan::math::initialize(lmu, DUMMY_VAR__);
            stan::math::fill(lmu,DUMMY_VAR__);
            current_statement_begin__ = 69;
            local_scalar_t__ p;
            (void) p;  // dummy to suppress unused var warning
            stan::math::initialize(p, DUMMY_VAR__);
            stan::math::fill(p,DUMMY_VAR__);
            current_statement_begin__ = 70;
            validate_non_negative_index("ltmp", "L", L);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  ltmp(static_cast<Eigen::VectorXd::Index>(L));
            (void) ltmp;  // dummy to suppress unused var warning
            stan::math::initialize(ltmp, DUMMY_VAR__);
            stan::math::fill(ltmp,DUMMY_VAR__);
            current_statement_begin__ = 71;
            validate_non_negative_index("esum", "L", L);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  esum(static_cast<Eigen::VectorXd::Index>(L));
            (void) esum;  // dummy to suppress unused var warning
            stan::math::initialize(esum, DUMMY_VAR__);
            stan::math::fill(esum,DUMMY_VAR__);
            current_statement_begin__ = 72;
            validate_non_negative_index("esum0", "L", L);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  esum0(static_cast<Eigen::VectorXd::Index>(L));
            (void) esum0;  // dummy to suppress unused var warning
            stan::math::initialize(esum0, DUMMY_VAR__);
            stan::math::fill(esum0,DUMMY_VAR__);
            current_statement_begin__ = 73;
            validate_non_negative_index("lpsa", "k", k);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  lpsa(static_cast<Eigen::VectorXd::Index>(k));
            (void) lpsa;  // dummy to suppress unused var warning
            stan::math::initialize(lpsa, DUMMY_VAR__);
            stan::math::fill(lpsa,DUMMY_VAR__);
            current_statement_begin__ = 74;
            validate_non_negative_index("lpsd", "k", k);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  lpsd(static_cast<Eigen::VectorXd::Index>(k));
            (void) lpsd;  // dummy to suppress unused var warning
            stan::math::initialize(lpsd, DUMMY_VAR__);
            stan::math::fill(lpsd,DUMMY_VAR__);
            current_statement_begin__ = 76;
            validate_non_negative_index("betasN", "K", K);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  betasN(static_cast<Eigen::VectorXd::Index>(K));
            (void) betasN;  // dummy to suppress unused var warning
            stan::math::initialize(betasN, DUMMY_VAR__);
            stan::math::fill(betasN,DUMMY_VAR__);
            current_statement_begin__ = 77;
            validate_non_negative_index("betasP", "K", K);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  betasP(static_cast<Eigen::VectorXd::Index>(K));
            (void) betasP;  // dummy to suppress unused var warning
            stan::math::initialize(betasP, DUMMY_VAR__);
            stan::math::fill(betasP,DUMMY_VAR__);
            current_statement_begin__ = 78;
            validate_non_negative_index("lmuN", "N", N);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  lmuN(static_cast<Eigen::VectorXd::Index>(N));
            (void) lmuN;  // dummy to suppress unused var warning
            stan::math::initialize(lmuN, DUMMY_VAR__);
            stan::math::fill(lmuN,DUMMY_VAR__);
            current_statement_begin__ = 79;
            validate_non_negative_index("lmuP", "N", N);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  lmuP(static_cast<Eigen::VectorXd::Index>(N));
            (void) lmuP;  // dummy to suppress unused var warning
            stan::math::initialize(lmuP, DUMMY_VAR__);
            stan::math::fill(lmuP,DUMMY_VAR__);
            current_statement_begin__ = 83;
            lp_accum__.add(gamma_log<propto__>(theta, 1, 0.10000000000000001));
            current_statement_begin__ = 84;
            lp_accum__.add(gamma_log<propto__>(phi, 1, 0.10000000000000001));
            current_statement_begin__ = 85;
            lp_accum__.add(normal_log<propto__>(anorm, 6, 4));
            current_statement_begin__ = 86;
            lp_accum__.add(normal_log<propto__>(apso, 6, 4));
            current_statement_begin__ = 87;
            for (int i = 1; i <= (K - 1); ++i) {
                current_statement_begin__ = 88;
                lp_accum__.add(cauchy_log<propto__>(get_base1(betas,i,"betas",1), 0, 2.5));
            }
            current_statement_begin__ = 92;
            for (int i = 1; i <= L; ++i) {
                current_statement_begin__ = 93;
                for (int t = 1; t <= 2; ++t) {
                    current_statement_begin__ = 94;
                    lp_accum__.add(normal_log<propto__>(get_base1(rai0,i,t,"rai0",1), get_base1(get_base1(ai0,i,"ai0",1),t,"ai0",2), get_base1(get_base1(sdai0,i,"sdai0",1),t,"sdai0",2)));
                }
            }
            current_statement_begin__ = 98;
            lp_accum__.add(normal_log<propto__>(ui, 0, sdnb));
            current_statement_begin__ = 99;
            lp_accum__.add(normal_log<propto__>(uasei, 0, sdase));
            current_statement_begin__ = 101;
            lp_accum__.add(cauchy_log<propto__>(sdnb, 0, 1));
            current_statement_begin__ = 103;
            lp_accum__.add(cauchy_log<propto__>(sdase, 0, 1));
            current_statement_begin__ = 106;
            for (int i = 1; i <= k; ++i) {
                current_statement_begin__ = 107;
                stan::model::assign(lpsa, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            (normal_log(ba,get_base1(aveP,i,"aveP",1),get_base1(sdP,i,"sdP",1)) + get_base1(mixP,i,"mixP",1)), 
                            "assigning variable lpsa");
                current_statement_begin__ = 108;
                stan::model::assign(lpsd, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            (normal_log(bd,get_base1(aveP,i,"aveP",1),get_base1(sdP,i,"sdP",1)) + get_base1(mixP,i,"mixP",1)), 
                            "assigning variable lpsd");
            }
            current_statement_begin__ = 110;
            lp_accum__.add(log_sum_exp(lpsa));
            current_statement_begin__ = 111;
            lp_accum__.add(log_sum_exp(lpsd));
            current_statement_begin__ = 115;
            stan::math::assign(pos, 1);
            current_statement_begin__ = 118;
            stan::math::assign(betasN, append_row(anorm,betas));
            current_statement_begin__ = 119;
            stan::math::assign(betasP, append_row(apso,betas));
            current_statement_begin__ = 120;
            stan::math::assign(lmuN, multiply(stan::model::rvalue(cov, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_min_max(2, cols(cov)), stan::model::nil_index_list())), "cov"),betasN));
            current_statement_begin__ = 121;
            stan::math::assign(lmuP, multiply(stan::model::rvalue(cov, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_min_max(2, cols(cov)), stan::model::nil_index_list())), "cov"),betasP));
            current_statement_begin__ = 126;
            for (int i = 1; i <= N; ++i) {
                current_statement_begin__ = 129;
                for (int t = 1; t <= 2; ++t) {
                    current_statement_begin__ = 131;
                    if (as_bool(logical_eq(t,1))) {
                        current_statement_begin__ = 133;
                        stan::math::assign(lmu, (get_base1(lmuP,i,"lmuP",1) + get_base1(ui,i,"ui",1)));
                        current_statement_begin__ = 134;
                        stan::math::assign(lmu, stan::model::deep_copy((logical_eq(stan::math::fabs(get_base1(g,i,"g",1)),1) ? stan::math::promote_scalar<local_scalar_t__>(((lmu + stan::math::log1p((1 + stan::math::exp(bp)))) - stan::math::log(2))) : stan::math::promote_scalar<local_scalar_t__>(lmu) )));
                        current_statement_begin__ = 135;
                        stan::math::assign(lmu, stan::model::deep_copy((logical_eq(get_base1(g,i,"g",1),2) ? stan::math::promote_scalar<local_scalar_t__>((lmu + bp)) : stan::math::promote_scalar<local_scalar_t__>(lmu) )));
                        current_statement_begin__ = 137;
                        lp_accum__.add(neg_binomial_2_log(get_base1(Y,i,"Y",1),stan::math::exp(lmu),phi));
                    } else {
                        current_statement_begin__ = 141;
                        stan::math::assign(lmu, (get_base1(lmuN,i,"lmuN",1) + get_base1(ui,i,"ui",1)));
                        current_statement_begin__ = 142;
                        stan::math::assign(lmu, stan::model::deep_copy((logical_eq(stan::math::fabs(get_base1(g,i,"g",1)),1) ? stan::math::promote_scalar<local_scalar_t__>(((lmu + stan::math::log1p((1 + stan::math::exp(bn)))) - stan::math::log(2))) : stan::math::promote_scalar<local_scalar_t__>(lmu) )));
                        current_statement_begin__ = 143;
                        stan::math::assign(lmu, stan::model::deep_copy((logical_eq(get_base1(g,i,"g",1),2) ? stan::math::promote_scalar<local_scalar_t__>((lmu + bn)) : stan::math::promote_scalar<local_scalar_t__>(lmu) )));
                        current_statement_begin__ = 145;
                        lp_accum__.add(neg_binomial_2_log(get_base1(Y,i,"Y",1),stan::math::exp(lmu),phi));
                    }
                }
            }
            current_statement_begin__ = 150;
            stan::math::assign(pos, 1);
            current_statement_begin__ = 152;
            for (int i = 1; i <= A; ++i) {
                current_statement_begin__ = 154;
                for (int t = 1; t <= 2; ++t) {
                    current_statement_begin__ = 155;
                    if (as_bool(logical_gt(get_base1(get_base1(m,i,"m",1),t,"m",2),0))) {
                        current_statement_begin__ = 156;
                        stan::math::assign(esum0, add(stan::model::rvalue(rai0, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(t), stan::model::nil_index_list())), "rai0"),get_base1(uasei,i,"uasei",1)));
                        current_statement_begin__ = 157;
                        if (as_bool(logical_eq(t,1))) {
                            current_statement_begin__ = 158;
                            stan::math::assign(esum, inv_logit(add(esum0,bp)));
                        } else {
                            current_statement_begin__ = 160;
                            stan::math::assign(esum, inv_logit(add(esum0,bn)));
                        }
                        current_statement_begin__ = 162;
                        for (int r = pos; r <= ((pos + get_base1(s,i,"s",1)) - 1); ++r) {
                            current_statement_begin__ = 164;
                            stan::math::assign(p, (logical_eq(get_base1(gase,i,"gase",1),1) ? stan::math::promote_scalar<local_scalar_t__>(get_base1(esum,r,"esum",1)) : stan::math::promote_scalar<local_scalar_t__>(inv_logit(get_base1(esum0,r,"esum0",1))) ));
                            current_statement_begin__ = 165;
                            stan::math::assign(p, stan::model::deep_copy((logical_eq(get_base1(gase,i,"gase",1),-(1)) ? stan::math::promote_scalar<local_scalar_t__>((1 - get_base1(esum,r,"esum",1))) : stan::math::promote_scalar<local_scalar_t__>(p) )));
                            current_statement_begin__ = 167;
                            stan::model::assign(ltmp, 
                                        stan::model::cons_list(stan::model::index_uni(r), stan::model::nil_index_list()), 
                                        (beta_binomial_log(get_base1(get_base1(n,r,"n",1),t,"n",2),get_base1(get_base1(m,i,"m",1),t,"m",2),(p * theta),((1 - p) * theta)) + stan::math::log(get_base1(pH,r,"pH",1))), 
                                        "assigning variable ltmp");
                        }
                        current_statement_begin__ = 169;
                        lp_accum__.add(log_sum_exp(stan::model::rvalue(ltmp, stan::model::cons_list(stan::model::index_min_max(pos, ((pos + get_base1(s,i,"s",1)) - 1)), stan::model::nil_index_list()), "ltmp")));
                    }
                }
                current_statement_begin__ = 172;
                stan::math::assign(pos, stan::model::deep_copy((pos + get_base1(s,i,"s",1))));
            }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("anorm");
        names__.push_back("apso");
        names__.push_back("ba");
        names__.push_back("bd");
        names__.push_back("phi");
        names__.push_back("theta");
        names__.push_back("betas");
        names__.push_back("rai0");
        names__.push_back("ui");
        names__.push_back("uasei");
        names__.push_back("sdnb");
        names__.push_back("sdase");
        names__.push_back("bp");
        names__.push_back("bn");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((K - 1));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(L);
        dims__.push_back(2);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(A);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);
        static const char* function__ = "model_paired_GT_nb_ase_refbias_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double anorm = in__.scalar_constrain();
        double apso = in__.scalar_constrain();
        double ba = in__.scalar_constrain();
        double bd = in__.scalar_constrain();
        double phi = in__.scalar_lb_constrain(0);
        double theta = in__.scalar_lb_constrain(0);
        vector_d betas = in__.vector_constrain((K - 1));
        matrix_d rai0 = in__.matrix_constrain(L,2);
        vector_d ui = in__.vector_constrain(N);
        vector_d uasei = in__.vector_constrain(A);
        double sdnb = in__.scalar_lb_constrain(0);
        double sdase = in__.scalar_lb_constrain(0);
        vars__.push_back(anorm);
        vars__.push_back(apso);
        vars__.push_back(ba);
        vars__.push_back(bd);
        vars__.push_back(phi);
        vars__.push_back(theta);
            for (int k_0__ = 0; k_0__ < (K - 1); ++k_0__) {
            vars__.push_back(betas[k_0__]);
            }
            for (int k_1__ = 0; k_1__ < 2; ++k_1__) {
                for (int k_0__ = 0; k_0__ < L; ++k_0__) {
                vars__.push_back(rai0(k_0__, k_1__));
                }
            }
            for (int k_0__ = 0; k_0__ < N; ++k_0__) {
            vars__.push_back(ui[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < A; ++k_0__) {
            vars__.push_back(uasei[k_0__]);
            }
        vars__.push_back(sdnb);
        vars__.push_back(sdase);
        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            current_statement_begin__ = 54;
            local_scalar_t__ bp;
            (void) bp;  // dummy to suppress unused var warning
            stan::math::initialize(bp, DUMMY_VAR__);
            stan::math::fill(bp,DUMMY_VAR__);
            current_statement_begin__ = 55;
            local_scalar_t__ bn;
            (void) bn;  // dummy to suppress unused var warning
            stan::math::initialize(bn, DUMMY_VAR__);
            stan::math::fill(bn,DUMMY_VAR__);
            current_statement_begin__ = 57;
            stan::math::assign(bp, (ba + bd));
            current_statement_begin__ = 58;
            stan::math::assign(bn, (ba - bd));
            // validate transformed parameters
            current_statement_begin__ = 54;
            current_statement_begin__ = 55;
            // write transformed parameters
            if (include_tparams__) {
        vars__.push_back(bp);
        vars__.push_back(bn);
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            // validate generated quantities
            // write generated quantities
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    static std::string model_name() {
        return "model_paired_GT_nb_ase_refbias";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "anorm";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "apso";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "ba";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "bd";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "phi";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "theta";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= (K - 1); ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "betas" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_1__ = 1; k_1__ <= 2; ++k_1__) {
            for (int k_0__ = 1; k_0__ <= L; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "rai0" << '.' << k_0__ << '.' << k_1__;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "ui" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= A; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "uasei" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sdnb";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sdase";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "bp";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "bn";
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__) return;
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "anorm";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "apso";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "ba";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "bd";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "phi";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "theta";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= (K - 1); ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "betas" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_1__ = 1; k_1__ <= 2; ++k_1__) {
            for (int k_0__ = 1; k_0__ <= L; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "rai0" << '.' << k_0__ << '.' << k_1__;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "ui" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= A; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "uasei" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sdnb";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sdase";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "bp";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "bn";
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__) return;
    }
}; // model
}
typedef model_paired_GT_nb_ase_refbias_namespace::model_paired_GT_nb_ase_refbias stan_model;
#endif
