// Generated by rstantools.  Do not edit by hand.

/*
    baseqtl is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    baseqtl is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with baseqtl.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_noGT_nb_ase_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_noGT_nb_ase");
    reader.add_event(113, 111, "end", "model_noGT_nb_ase");
    return reader;
}
#include <stan_meta_header.hpp>
class model_noGT_nb_ase
  : public stan::model::model_base_crtp<model_noGT_nb_ase> {
private:
        int N;
        int G;
        int A;
        int L;
        int K;
        int k;
        std::vector<int> Y;
        std::vector<int> sNB;
        vector_d gNB;
        vector_d pNB;
        std::vector<int> gase;
        std::vector<int> m;
        std::vector<int> n;
        vector_d pH;
        std::vector<int> s;
        matrix_d cov;
        std::vector<std::vector<int> > ASEi;
        std::vector<int> h2g;
        vector_d aveP;
        vector_d sdP;
        vector_d mixP;
        int Max;
public:
    model_noGT_nb_ase(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_noGT_nb_ase(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_noGT_nb_ase_namespace::model_noGT_nb_ase";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 4;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            check_greater_or_equal(function__, "N", N, 0);
            current_statement_begin__ = 5;
            context__.validate_dims("data initialization", "G", "int", context__.to_vec());
            G = int(0);
            vals_i__ = context__.vals_i("G");
            pos__ = 0;
            G = vals_i__[pos__++];
            check_greater_or_equal(function__, "G", G, 0);
            current_statement_begin__ = 6;
            context__.validate_dims("data initialization", "A", "int", context__.to_vec());
            A = int(0);
            vals_i__ = context__.vals_i("A");
            pos__ = 0;
            A = vals_i__[pos__++];
            check_greater_or_equal(function__, "A", A, 0);
            current_statement_begin__ = 7;
            context__.validate_dims("data initialization", "L", "int", context__.to_vec());
            L = int(0);
            vals_i__ = context__.vals_i("L");
            pos__ = 0;
            L = vals_i__[pos__++];
            check_greater_or_equal(function__, "L", L, 0);
            current_statement_begin__ = 8;
            context__.validate_dims("data initialization", "K", "int", context__.to_vec());
            K = int(0);
            vals_i__ = context__.vals_i("K");
            pos__ = 0;
            K = vals_i__[pos__++];
            check_greater_or_equal(function__, "K", K, 0);
            current_statement_begin__ = 9;
            context__.validate_dims("data initialization", "k", "int", context__.to_vec());
            k = int(0);
            vals_i__ = context__.vals_i("k");
            pos__ = 0;
            k = vals_i__[pos__++];
            check_greater_or_equal(function__, "k", k, 0);
            current_statement_begin__ = 10;
            validate_non_negative_index("Y", "N", N);
            context__.validate_dims("data initialization", "Y", "int", context__.to_vec(N));
            Y = std::vector<int>(N, int(0));
            vals_i__ = context__.vals_i("Y");
            pos__ = 0;
            size_t Y_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < Y_k_0_max__; ++k_0__) {
                Y[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 11;
            validate_non_negative_index("sNB", "N", N);
            context__.validate_dims("data initialization", "sNB", "int", context__.to_vec(N));
            sNB = std::vector<int>(N, int(0));
            vals_i__ = context__.vals_i("sNB");
            pos__ = 0;
            size_t sNB_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < sNB_k_0_max__; ++k_0__) {
                sNB[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 12;
            validate_non_negative_index("gNB", "G", G);
            context__.validate_dims("data initialization", "gNB", "vector_d", context__.to_vec(G));
            gNB = Eigen::Matrix<double, Eigen::Dynamic, 1>(G);
            vals_r__ = context__.vals_r("gNB");
            pos__ = 0;
            size_t gNB_j_1_max__ = G;
            for (size_t j_1__ = 0; j_1__ < gNB_j_1_max__; ++j_1__) {
                gNB(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 13;
            validate_non_negative_index("pNB", "G", G);
            context__.validate_dims("data initialization", "pNB", "vector_d", context__.to_vec(G));
            pNB = Eigen::Matrix<double, Eigen::Dynamic, 1>(G);
            vals_r__ = context__.vals_r("pNB");
            pos__ = 0;
            size_t pNB_j_1_max__ = G;
            for (size_t j_1__ = 0; j_1__ < pNB_j_1_max__; ++j_1__) {
                pNB(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 14;
            validate_non_negative_index("gase", "L", L);
            context__.validate_dims("data initialization", "gase", "int", context__.to_vec(L));
            gase = std::vector<int>(L, int(0));
            vals_i__ = context__.vals_i("gase");
            pos__ = 0;
            size_t gase_k_0_max__ = L;
            for (size_t k_0__ = 0; k_0__ < gase_k_0_max__; ++k_0__) {
                gase[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 15;
            validate_non_negative_index("m", "A", A);
            context__.validate_dims("data initialization", "m", "int", context__.to_vec(A));
            m = std::vector<int>(A, int(0));
            vals_i__ = context__.vals_i("m");
            pos__ = 0;
            size_t m_k_0_max__ = A;
            for (size_t k_0__ = 0; k_0__ < m_k_0_max__; ++k_0__) {
                m[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 16;
            validate_non_negative_index("n", "L", L);
            context__.validate_dims("data initialization", "n", "int", context__.to_vec(L));
            n = std::vector<int>(L, int(0));
            vals_i__ = context__.vals_i("n");
            pos__ = 0;
            size_t n_k_0_max__ = L;
            for (size_t k_0__ = 0; k_0__ < n_k_0_max__; ++k_0__) {
                n[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 17;
            validate_non_negative_index("pH", "L", L);
            context__.validate_dims("data initialization", "pH", "vector_d", context__.to_vec(L));
            pH = Eigen::Matrix<double, Eigen::Dynamic, 1>(L);
            vals_r__ = context__.vals_r("pH");
            pos__ = 0;
            size_t pH_j_1_max__ = L;
            for (size_t j_1__ = 0; j_1__ < pH_j_1_max__; ++j_1__) {
                pH(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 18;
            validate_non_negative_index("s", "A", A);
            context__.validate_dims("data initialization", "s", "int", context__.to_vec(A));
            s = std::vector<int>(A, int(0));
            vals_i__ = context__.vals_i("s");
            pos__ = 0;
            size_t s_k_0_max__ = A;
            for (size_t k_0__ = 0; k_0__ < s_k_0_max__; ++k_0__) {
                s[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 19;
            validate_non_negative_index("cov", "N", N);
            validate_non_negative_index("cov", "(1 + K)", (1 + K));
            context__.validate_dims("data initialization", "cov", "matrix_d", context__.to_vec(N,(1 + K)));
            cov = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(N, (1 + K));
            vals_r__ = context__.vals_r("cov");
            pos__ = 0;
            size_t cov_j_2_max__ = (1 + K);
            size_t cov_j_1_max__ = N;
            for (size_t j_2__ = 0; j_2__ < cov_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < cov_j_1_max__; ++j_1__) {
                    cov(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 20;
            validate_non_negative_index("ASEi", "N", N);
            validate_non_negative_index("ASEi", "2", 2);
            context__.validate_dims("data initialization", "ASEi", "int", context__.to_vec(N,2));
            ASEi = std::vector<std::vector<int> >(N, std::vector<int>(2, int(0)));
            vals_i__ = context__.vals_i("ASEi");
            pos__ = 0;
            size_t ASEi_k_0_max__ = N;
            size_t ASEi_k_1_max__ = 2;
            for (size_t k_1__ = 0; k_1__ < ASEi_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < ASEi_k_0_max__; ++k_0__) {
                    ASEi[k_0__][k_1__] = vals_i__[pos__++];
                }
            }
            current_statement_begin__ = 21;
            validate_non_negative_index("h2g", "G", G);
            context__.validate_dims("data initialization", "h2g", "int", context__.to_vec(G));
            h2g = std::vector<int>(G, int(0));
            vals_i__ = context__.vals_i("h2g");
            pos__ = 0;
            size_t h2g_k_0_max__ = G;
            for (size_t k_0__ = 0; k_0__ < h2g_k_0_max__; ++k_0__) {
                h2g[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 22;
            validate_non_negative_index("aveP", "k", k);
            context__.validate_dims("data initialization", "aveP", "vector_d", context__.to_vec(k));
            aveP = Eigen::Matrix<double, Eigen::Dynamic, 1>(k);
            vals_r__ = context__.vals_r("aveP");
            pos__ = 0;
            size_t aveP_j_1_max__ = k;
            for (size_t j_1__ = 0; j_1__ < aveP_j_1_max__; ++j_1__) {
                aveP(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 23;
            validate_non_negative_index("sdP", "k", k);
            context__.validate_dims("data initialization", "sdP", "vector_d", context__.to_vec(k));
            sdP = Eigen::Matrix<double, Eigen::Dynamic, 1>(k);
            vals_r__ = context__.vals_r("sdP");
            pos__ = 0;
            size_t sdP_j_1_max__ = k;
            for (size_t j_1__ = 0; j_1__ < sdP_j_1_max__; ++j_1__) {
                sdP(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 24;
            validate_non_negative_index("mixP", "k", k);
            context__.validate_dims("data initialization", "mixP", "vector_d", context__.to_vec(k));
            mixP = Eigen::Matrix<double, Eigen::Dynamic, 1>(k);
            vals_r__ = context__.vals_r("mixP");
            pos__ = 0;
            size_t mixP_j_1_max__ = k;
            for (size_t j_1__ = 0; j_1__ < mixP_j_1_max__; ++j_1__) {
                mixP(j_1__) = vals_r__[pos__++];
            }
            // initialize transformed data variables
            current_statement_begin__ = 30;
            Max = int(0);
            stan::math::fill(Max, std::numeric_limits<int>::min());
            // execute transformed data statements
            current_statement_begin__ = 31;
            stan::math::assign(Max, max(h2g));
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 37;
            validate_non_negative_index("betas", "K", K);
            num_params_r__ += K;
            current_statement_begin__ = 38;
            num_params_r__ += 1;
            current_statement_begin__ = 39;
            num_params_r__ += 1;
            current_statement_begin__ = 40;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_noGT_nb_ase() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 37;
        if (!(context__.contains_r("betas")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable betas missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("betas");
        pos__ = 0U;
        validate_non_negative_index("betas", "K", K);
        context__.validate_dims("parameter initialization", "betas", "vector_d", context__.to_vec(K));
        Eigen::Matrix<double, Eigen::Dynamic, 1> betas(K);
        size_t betas_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < betas_j_1_max__; ++j_1__) {
            betas(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(betas);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable betas: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 38;
        if (!(context__.contains_r("bj")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable bj missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("bj");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "bj", "double", context__.to_vec());
        double bj(0);
        bj = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(bj);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable bj: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 39;
        if (!(context__.contains_r("phi")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable phi missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("phi");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "phi", "double", context__.to_vec());
        double phi(0);
        phi = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, phi);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable phi: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 40;
        if (!(context__.contains_r("theta")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable theta missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("theta");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "theta", "double", context__.to_vec());
        double theta(0);
        theta = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, theta);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable theta: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 37;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> betas;
            (void) betas;  // dummy to suppress unused var warning
            if (jacobian__)
                betas = in__.vector_constrain(K, lp__);
            else
                betas = in__.vector_constrain(K);
            current_statement_begin__ = 38;
            local_scalar_t__ bj;
            (void) bj;  // dummy to suppress unused var warning
            if (jacobian__)
                bj = in__.scalar_constrain(lp__);
            else
                bj = in__.scalar_constrain();
            current_statement_begin__ = 39;
            local_scalar_t__ phi;
            (void) phi;  // dummy to suppress unused var warning
            if (jacobian__)
                phi = in__.scalar_lb_constrain(0, lp__);
            else
                phi = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 40;
            local_scalar_t__ theta;
            (void) theta;  // dummy to suppress unused var warning
            if (jacobian__)
                theta = in__.scalar_lb_constrain(0, lp__);
            else
                theta = in__.scalar_lb_constrain(0);
            // model body
            {
            current_statement_begin__ = 46;
            int pos(0);
            (void) pos;  // dummy to suppress unused var warning
            stan::math::fill(pos, std::numeric_limits<int>::min());
            current_statement_begin__ = 47;
            int posl(0);
            (void) posl;  // dummy to suppress unused var warning
            stan::math::fill(posl, std::numeric_limits<int>::min());
            current_statement_begin__ = 48;
            validate_non_negative_index("lmu1", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> lmu1(N);
            stan::math::initialize(lmu1, DUMMY_VAR__);
            stan::math::fill(lmu1, DUMMY_VAR__);
            current_statement_begin__ = 49;
            local_scalar_t__ lmu(DUMMY_VAR__);
            (void) lmu;  // dummy to suppress unused var warning
            stan::math::initialize(lmu, DUMMY_VAR__);
            stan::math::fill(lmu, DUMMY_VAR__);
            current_statement_begin__ = 50;
            validate_non_negative_index("ltmp", "G", G);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> ltmp(G);
            stan::math::initialize(ltmp, DUMMY_VAR__);
            stan::math::fill(ltmp, DUMMY_VAR__);
            current_statement_begin__ = 51;
            local_scalar_t__ ebj(DUMMY_VAR__);
            (void) ebj;  // dummy to suppress unused var warning
            stan::math::initialize(ebj, DUMMY_VAR__);
            stan::math::fill(ebj, DUMMY_VAR__);
            current_statement_begin__ = 52;
            local_scalar_t__ ebjd(DUMMY_VAR__);
            (void) ebjd;  // dummy to suppress unused var warning
            stan::math::initialize(ebjd, DUMMY_VAR__);
            stan::math::fill(ebjd, DUMMY_VAR__);
            current_statement_begin__ = 53;
            local_scalar_t__ p(DUMMY_VAR__);
            (void) p;  // dummy to suppress unused var warning
            stan::math::initialize(p, DUMMY_VAR__);
            stan::math::fill(p, DUMMY_VAR__);
            current_statement_begin__ = 54;
            validate_non_negative_index("ase", "Max", Max);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> ase(Max);
            stan::math::initialize(ase, DUMMY_VAR__);
            stan::math::fill(ase, DUMMY_VAR__);
            current_statement_begin__ = 55;
            local_scalar_t__ sAse(DUMMY_VAR__);
            (void) sAse;  // dummy to suppress unused var warning
            stan::math::initialize(sAse, DUMMY_VAR__);
            stan::math::fill(sAse, DUMMY_VAR__);
            current_statement_begin__ = 56;
            validate_non_negative_index("lps", "k", k);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> lps(k);
            stan::math::initialize(lps, DUMMY_VAR__);
            stan::math::fill(lps, DUMMY_VAR__);
            current_statement_begin__ = 59;
            lp_accum__.add(gamma_log<propto__>(theta, 1, 0.1));
            current_statement_begin__ = 60;
            lp_accum__.add(gamma_log<propto__>(phi, 1, 0.1));
            current_statement_begin__ = 61;
            lp_accum__.add(normal_log<propto__>(get_base1(betas, 1, "betas", 1), 6, 4));
            current_statement_begin__ = 62;
            for (int i = 2; i <= K; ++i) {
                current_statement_begin__ = 63;
                lp_accum__.add(cauchy_log<propto__>(get_base1(betas, i, "betas", 1), 0, 2.5));
            }
            current_statement_begin__ = 66;
            for (int i = 1; i <= k; ++i) {
                current_statement_begin__ = 67;
                stan::model::assign(lps, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            (normal_log(bj, get_base1(aveP, i, "aveP", 1), get_base1(sdP, i, "sdP", 1)) + get_base1(mixP, i, "mixP", 1)), 
                            "assigning variable lps");
            }
            current_statement_begin__ = 69;
            lp_accum__.add(log_sum_exp(lps));
            current_statement_begin__ = 73;
            stan::math::assign(pos, 1);
            current_statement_begin__ = 74;
            stan::math::assign(posl, 1);
            current_statement_begin__ = 75;
            stan::math::assign(ase, rep_vector(0, Max));
            current_statement_begin__ = 76;
            stan::math::assign(ebj, stan::math::exp(bj));
            current_statement_begin__ = 77;
            stan::math::assign(ebjd, (ebj * inv((ebj + 1))));
            current_statement_begin__ = 78;
            stan::math::assign(lmu1, multiply(stan::model::rvalue(cov, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_min_max(2, cols(cov)), stan::model::nil_index_list())), "cov"), betas));
            current_statement_begin__ = 80;
            for (int i = 1; i <= N; ++i) {
                current_statement_begin__ = 82;
                for (int r = pos; r <= ((pos + get_base1(sNB, i, "sNB", 1)) - 1); ++r) {
                    current_statement_begin__ = 84;
                    stan::math::assign(lmu, (logical_eq(stan::math::fabs(get_base1(gNB, r, "gNB", 1)), 1) ? stan::math::promote_scalar<local_scalar_t__>(((get_base1(lmu1, i, "lmu1", 1) + stan::math::log1p(ebj)) - stan::math::log(2))) : stan::math::promote_scalar<local_scalar_t__>(get_base1(lmu1, i, "lmu1", 1)) ));
                    current_statement_begin__ = 86;
                    stan::math::assign(lmu, (logical_eq(get_base1(gNB, r, "gNB", 1), 2) ? stan::math::promote_scalar<local_scalar_t__>((lmu + bj)) : stan::math::promote_scalar<local_scalar_t__>(lmu) ));
                    current_statement_begin__ = 88;
                    stan::model::assign(ltmp, 
                                stan::model::cons_list(stan::model::index_uni(r), stan::model::nil_index_list()), 
                                (neg_binomial_2_log(get_base1(Y, i, "Y", 1), stan::math::exp(lmu), phi) + stan::math::log(get_base1(pNB, r, "pNB", 1))), 
                                "assigning variable ltmp");
                    current_statement_begin__ = 90;
                    if (as_bool(logical_eq(get_base1(get_base1(ASEi, i, "ASEi", 1), 1, "ASEi", 2), 1))) {
                        current_statement_begin__ = 92;
                        for (int x = 1; x <= get_base1(h2g, r, "h2g", 1); ++x) {
                            current_statement_begin__ = 94;
                            stan::math::assign(p, (logical_eq(get_base1(gase, posl, "gase", 1), 1) ? stan::math::promote_scalar<local_scalar_t__>(ebjd) : stan::math::promote_scalar<local_scalar_t__>(0.5) ));
                            current_statement_begin__ = 95;
                            stan::math::assign(p, (logical_eq(get_base1(gase, posl, "gase", 1), -(1)) ? stan::math::promote_scalar<local_scalar_t__>((1 - ebjd)) : stan::math::promote_scalar<local_scalar_t__>(p) ));
                            current_statement_begin__ = 96;
                            stan::model::assign(ase, 
                                        stan::model::cons_list(stan::model::index_uni(x), stan::model::nil_index_list()), 
                                        (beta_binomial_log(get_base1(n, posl, "n", 1), get_base1(m, get_base1(get_base1(ASEi, i, "ASEi", 1), 2, "ASEi", 2), "m", 1), (p * theta), ((1 - p) * theta)) + stan::math::log(get_base1(pH, posl, "pH", 1))), 
                                        "assigning variable ase");
                            current_statement_begin__ = 98;
                            stan::math::assign(posl, (posl + 1));
                        }
                        current_statement_begin__ = 100;
                        stan::math::assign(sAse, log_sum_exp(stan::model::rvalue(ase, stan::model::cons_list(stan::model::index_min_max(1, get_base1(h2g, r, "h2g", 1)), stan::model::nil_index_list()), "ase")));
                        current_statement_begin__ = 101;
                        lp_accum__.add(log_sum_exp(get_base1(ltmp, r, "ltmp", 1), sAse));
                    }
                }
                current_statement_begin__ = 104;
                if (as_bool(logical_eq(get_base1(get_base1(ASEi, i, "ASEi", 1), 1, "ASEi", 2), 0))) {
                    current_statement_begin__ = 105;
                    lp_accum__.add(log_sum_exp(stan::model::rvalue(ltmp, stan::model::cons_list(stan::model::index_min_max(pos, ((pos + get_base1(sNB, i, "sNB", 1)) - 1)), stan::model::nil_index_list()), "ltmp")));
                }
                current_statement_begin__ = 108;
                stan::math::assign(pos, (pos + get_base1(sNB, i, "sNB", 1)));
            }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("betas");
        names__.push_back("bj");
        names__.push_back("phi");
        names__.push_back("theta");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_noGT_nb_ase_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        Eigen::Matrix<double, Eigen::Dynamic, 1> betas = in__.vector_constrain(K);
        size_t betas_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < betas_j_1_max__; ++j_1__) {
            vars__.push_back(betas(j_1__));
        }
        double bj = in__.scalar_constrain();
        vars__.push_back(bj);
        double phi = in__.scalar_lb_constrain(0);
        vars__.push_back(phi);
        double theta = in__.scalar_lb_constrain(0);
        vars__.push_back(theta);
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            if (!include_gqs__ && !include_tparams__) return;
            if (!include_gqs__) return;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_noGT_nb_ase";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t betas_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < betas_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "betas" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "bj";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "phi";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "theta";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t betas_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < betas_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "betas" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "bj";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "phi";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "theta";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
}; // model
}  // namespace
typedef model_noGT_nb_ase_namespace::model_noGT_nb_ase stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
