# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("GT_nb", "GT_nb_ase", "GT_nb_ase_refbias", "noGT2T_nb_ase", "noGT2T_nb_ase_refbias", "noGT_nb", "noGT_nb_ase", "noGT_nb_ase_refbias", "paired_GT_nb", "paired_GT_nb_ase", "paired_GT_nb_ase_refbias")

# load each stan module
Rcpp::loadModule("stan_fit4GT_nb_mod", what = TRUE)
Rcpp::loadModule("stan_fit4GT_nb_ase_mod", what = TRUE)
Rcpp::loadModule("stan_fit4GT_nb_ase_refbias_mod", what = TRUE)
Rcpp::loadModule("stan_fit4noGT2T_nb_ase_mod", what = TRUE)
Rcpp::loadModule("stan_fit4noGT2T_nb_ase_refbias_mod", what = TRUE)
Rcpp::loadModule("stan_fit4noGT_nb_mod", what = TRUE)
Rcpp::loadModule("stan_fit4noGT_nb_ase_mod", what = TRUE)
Rcpp::loadModule("stan_fit4noGT_nb_ase_refbias_mod", what = TRUE)
Rcpp::loadModule("stan_fit4paired_GT_nb_mod", what = TRUE)
Rcpp::loadModule("stan_fit4paired_GT_nb_ase_mod", what = TRUE)
Rcpp::loadModule("stan_fit4paired_GT_nb_ase_refbias_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
